import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import { Toaster } from "@/components/ui/toaster";
import { currentUser } from "@clerk/nextjs";
import connectDB from "@/lib/db-connect";
import checkAndMake from "@/lib/check-and-make";
const inter = Inter({ subsets: ["latin"] });
import Head from "next/head";
import Script from "next/script";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const user = await currentUser();
  await connectDB();
  // await checkAndMake(user?.emailAddresses[0].emailAddress);

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>{children}</body>
        <Toaster></Toaster>
      </html>
    </ClerkProvider>
  );
}
